cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_cart, name='cart'),
    path('add/<item_id>', views.add_to_cart, name='add_to_cart'),
    path('adjust/<item_id>/', views.adjust_cart, name='adjust_cart'),
    path('remove/<item_id>/', views.remove_from_cart, name='remove_from_cart'),
]

myfitness/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('programs/', include('programs.urls')),
    path('about/', include('about.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.profile, name='profile'),
    path('order_history/<order_number>',
         views.order_history, name='order_history'),
]

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

from django_countries.fields import CountryField


class UserProfile(models.Model):
    """
    A model to handle the user profile.
    Handling order history and delivery information
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    default_full_name = models.CharField(max_length=254, null=True, blank=True)
    default_email = models.EmailField(max_length=254, null=True, blank=True)
    default_phone_number = models.CharField(
        max_length=20, null=True, blank=True)
    default_street_address1 = models.CharField(
        max_length=80, null=True, blank=True)
    default_street_address2 = models.CharField(
        max_length=80, null=True, blank=True)
    default_town_or_city = models.CharField(
        max_length=40, null=True, blank=True)
    default_postcode = models.CharField(max_length=20, null=True, blank=True)
    default_county = models.CharField(max_length=80, null=True, blank=True)
    default_country = CountryField(
        blank_label='Country', null=True, blank=True)

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    """
    Create or update user profile
    """
    if created:
        UserProfile.objects.create(user=instance)
    # If user already exist, just save user profile
    instance.userprofile.save()

profiles/forms.py
from django import forms
from .models import UserProfile


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        exclude = ('user', )

    def __init__(self, *args, **kwargs):
        """
        Adding placeholders and classes, removing auto-generated
        labels and set autofocus to 'Full Name' field
        """
        super().__init__(*args, **kwargs)
        placeholders = {
            'default_full_name': 'Full Name',
            'default_email': 'E-mail',
            'default_phone_number': 'Phone Number',
            'default_postcode': 'Postal Code',
            'default_town_or_city': 'Town or City',
            'default_street_address1': 'Street Address 1',
            'default_street_address2': 'Street Address 2',
            'default_county': 'County or State',
        }

        self.fields['default_full_name'].widget.attrs['autofocus'] = True
        for field in self.fields:
            if field != 'default_country':
                if self.fields[field].required:
                    placeholder = f'{placeholders[field]} *'
                else:
                    placeholder = placeholders[field]
                self.fields[field].widget.attrs['placeholder'] = placeholder
            self.fields[field].widget.attrs['class'] = 'border border-black\
                                             rounded-0 profile-form-input'
            self.fields[field].label = False

profiles/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from .models import UserProfile
from .forms import UserProfileForm
from checkout.models import Order


@login_required
def profile(request):
    """ A view to display the user profiles and order history """
    profile = get_object_or_404(UserProfile, user=request.user)

    if request.method == 'POST':
        form = UserProfileForm(request.POST, instance=profile)
        if form.is_valid():
            form.save()
            messages.success(request, 'Profile successfully updated!')
        else:
            messages.error(request,
                           'Failed to update profile. Ensure form is valid')
    else:
        form = UserProfileForm(instance=profile)

    orders = profile.orders.all()

    template = 'profiles/profile.html'
    context = {
        'orders': orders,
        'form': form,
        'on_profile_page': True,
    }

    return render(request, template, context)


def order_history(request, order_number):
    order = get_object_or_404(Order, order_number=order_number)

    messages.info(request, (
        f'This is a confirmation for order {order_number} placed on {order.date}.\
        A confirmation email was sent on the order date'
    ))

    template = 'checkout/checkout_success.html'
    context = {
        'order': order,
        'from_profile': True,
    }

    return render(request, template, context)

profiles/templates/profiles/profile.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'profiles/css/profile.css' %}">
{% endblock %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="body-container container-fluid px-1 px-sm-3 my-1 my-sm-3">
        <div class="row body-products justify-content-center mx-0">
            <div class="row w-100">
                <div class="col text-center mt-3">
                    <!--  Header Text  -->
                    <h3 class="text-muted">My Profile</h3>
                    <hr class="w-75 mb-3">
                </div>
            </div>
            <div id="profile-info" class="row w-100 m-1 m-md-3 justify-content-center">
                <!--  Accordion for personal info and order history. Structure from Bootstrap  -->
                <!--  Automaticly showing personal information.  -->
                <div id="accordion" class="col-12 col-md-10 col-lg-7 p-0 profile-accordion">
                    <div class="card border-0">
                        <div class="card-header p-0" id="headingOne">
                            <button class="btn btn-wht btn-lg px-0 w-100 text-center" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                            <u>Delivery Information</u>
                            </button>
                        </div>
                        <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
                            <div class="card-body p-3 border border-top-0 rounded-0">
                                <form action="{% url 'profile' %}" method="POST" id="profile-update-form">
                                    {% csrf_token %}
                                    {{ form|crispy }}
                                    <button class="btn btn-black rounded-0">Submit Changes</button>
                                </form>
                            </div>
                        </div>
                    </div>
                    <!--  Order history  -->
                    <div class="card border-0">
                        <div class="card-header p-0" id="headingTwo">
                            <button class="btn btn-wht btn-lg collapsed px-0 w-100 text-center" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                            <u>Order History</u>
                            </button>
                        </div>
                        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
                            <div class="card-body p-3 border border-top-0 rounded-0 order-history">
                                <table class="table table-sm table-borderless">
                                    <thead>
                                        <th>Order Number</th>
                                        <th>Date</th>
                                        <th>Items</th>
                                        <th>Order Total</th>
                                    </thead>
                                    <tbody>
                                        {% for order in orders %}
                                            <tr>
                                                <td>
                                                    <a href="{% url 'order_history' order.order_number %}" title="{{ order.order_number }}">
                                                        {{ order.order_number|truncatechars:6 }}
                                                    </a>
                                                </td>
                                                <td>
                                                    {{ order.date }}
                                                </td>
                                                <td>
                                                    <ul class="list-unstyled">
                                                        {% for item in order.lineitems.all %}
                                                            <li class="small">
                                                                {{ item.product.friendly_name }} x {{ item.quantity }}
                                                            </li>
                                                        {% endfor %}
                                                    </ul>
                                                </td>
                                                <td>
                                                    ${{ order.grand_total }}
                                                </td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row w-100">
                <div class="col text-center mt-3">
                    <hr class="w-75 mb-3">
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block page_footer %}
    <div class="container footer-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'profiles/js/profile.js' %}">
    </script>
    {% if user.is_authenticated %}
        {% if user.first_name %}
            <script type="text/javascript">
                // Automatically add users name to form
                var fullName = "{{ user.first_name }} {{ user.last_name }}";
                $('#id_default_full_name').val(fullName);
                var userEmail = "{{ user.email }}";
                $('#id_default_email').val(userEmail);
            </script>
        {% endif %}
    {% endif %}
{% endblock %}