cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_cart, name='cart'),
    path('add/<item_id>', views.add_to_cart, name='add_to_cart'),
    path('adjust/<item_id>/', views.adjust_cart, name='adjust_cart'),
    path('remove/<item_id>/', views.remove_from_cart, name='remove_from_cart'),
]

checkout/urls.py
from django.urls import path
from . import views
from .webhooks import webhook


urlpatterns = [
    path('', views.checkout, name='checkout'),
    path(
        'checkout_success/<order_number>/',
        views.checkout_success,
        name='checkout_success',
    ),
    path(
        'cache_checkout_data/',
        views.cache_checkout_data,
        name='cache_checkout_data',
    ),
    path('wh/', webhook, name='webhook'),
]

myfitness/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('programs/', include('programs.urls')),
    path('about/', include('about.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

checkout/models.py
import uuid

from django.db import models
from django.db.models import Sum
from django.conf import settings

from django_countries.fields import CountryField

from products.models import Product
from profiles.models import UserProfile


class Order(models.Model):
    order_number = models.CharField(max_length=32, null=False, editable=False)
    user_profile = models.ForeignKey(
        UserProfile, on_delete=models.SET_NULL,
        null=True, blank=True, related_name='orders')
    full_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    country = CountryField(blank_label='Country *', null=False, blank=False)
    postcode = models.CharField(max_length=20, null=True, blank=True)
    town_or_city = models.CharField(max_length=40, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False)
    street_address2 = models.CharField(max_length=80, null=True, blank=True)
    county = models.CharField(max_length=80, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    delivery_cost = models.DecimalField(
        max_digits=6, decimal_places=2, null=False, default=0)
    order_total = models.DecimalField(
        max_digits=10, decimal_places=2, null=False, default=0)
    grand_total = models.DecimalField(
        max_digits=10, decimal_places=2, null=False, default=0)
    original_cart = models.TextField(null=False, blank=False, default='')
    stripe_pid = models.CharField(
        max_length=254, null=False, blank=False, default='')

    def _generate_order_number(self):
        """ Generate a random and unique order number with UUID """
        return uuid.uuid4().hex.upper()

    def update_total(self):
        """
        Update grand total when a new line item is added,
        also accounting delivery costs
        """
        self.order_total = self.lineitems.aggregate(
            Sum('lineitem_total'))['lineitem_total__sum'] or 0
        if self.order_total < settings.FREE_DELIVERY_THRESHOLD:
            self.delivery_cost = self.order_total * \
                settings.STANDARD_DELIVERY_PERCENTAGE / 100
        else:
            self.delivery_cost = 0
        self.grand_total = self.order_total + self.delivery_cost
        self.save()

    def save(self, *args, **kwargs):
        """
        Overriding save method to set order
        number if that has not already been set
        """
        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number


class OrderLineItem(models.Model):
    order = models.ForeignKey(
        Order, null=False, blank=False,
        on_delete=models.CASCADE, related_name='lineitems')
    product = models.ForeignKey(
        Product, null=False, blank=False, on_delete=models.CASCADE)
    quantity = models.IntegerField(null=False, blank=False, default=0)
    lineitem_total = models.DecimalField(
        max_digits=6, decimal_places=2,
        null=False, blank=False, editable=False)

    def save(self, *args, **kwargs):
        """
        Overriding save method to set the
        lineitem total and update grand total
        """
        self.lineitem_total = self.product.brand.price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f'SKU {self.product.sku} on order {self.order.order_number}'

checkout/forms.py
from django import forms
from .models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = (
            'full_name',
            'email',
            'phone_number',
            'street_address1',
            'street_address2',
            'town_or_city',
            'postcode',
            'country',
            'county',)

    def __init__(self, *args, **kwargs):
        """
        Adding placeholders and classes, removing auto-generated
        labels and set autofocus to 'Full Name' field
        """
        super().__init__(*args, **kwargs)
        placeholders = {
            'full_name': 'Full Name',
            'email': 'Email Address',
            'phone_number': 'Phone Number',
            'postcode': 'Postal Code',
            'town_or_city': 'Town or City',
            'street_address1': 'Street Address 1',
            'street_address2': 'Street Address 2',
            'county': 'County or State',
        }

        self.fields['full_name'].widget.attrs['autofocus'] = True
        for field in self.fields:
            if field != 'country':
                if self.fields[field].required:
                    placeholder = f'{placeholders[field]} *'
                else:
                    placeholder = placeholders[field]
                self.fields[field].widget.attrs['placeholder'] = placeholder
            self.fields[field].widget.attrs['class'] = 'stripe-style-input'
            self.fields[field].label = False

checkout/views.py
from django.shortcuts import (
    render, redirect, reverse, get_object_or_404, HttpResponse)
from django.views.decorators.http import require_POST
from django.contrib import messages
from django.conf import settings

from .forms import OrderForm
from .models import Order, OrderLineItem
from products.models import Product
from cart.contexts import cart_contents
from profiles.models import UserProfile
from profiles.forms import UserProfileForm

import stripe
import json


@require_POST
def cache_checkout_data(request):
    """ A view to handle cache checkout data """
    try:
        pid = request.POST.get('client_secret').split('_secret')[0]
        stripe.api_key = settings.STRIPE_SECRET_KEY
        stripe.PaymentIntent.modify(pid, metadata={
            'cart': json.dumps(request.session.get('cart', {})),
            'save_info': request.POST.get('save_info'),
            'username': request.user,
        })
        return HttpResponse(status=200)
    except Exception as e:
        messages.error(request, "Something went wrong. We can't process \
            your payment at the moment. Please try again later.")
        return HttpResponse(content=e, status=400)


def checkout(request):
    """
    A view to handle the collect the cart if it exists and set up a checkout.
    """
    stripe_public_key = settings.STRIPE_PUBLIC_KEY
    stripe_secret_key = settings.STRIPE_SECRET_KEY

    if request.method == 'POST':
        cart = request.session.get('cart', {})

        form_data = {
            'full_name': request.POST['full_name'],
            'email': request.POST['email'],
            'phone_number': request.POST['phone_number'],
            'country': request.POST['country'],
            'postcode': request.POST['postcode'],
            'town_or_city': request.POST['town_or_city'],
            'street_address1': request.POST['street_address1'],
            'street_address2': request.POST['street_address2'],
            'county': request.POST['county'],
        }

        order_form = OrderForm(form_data)
        if order_form.is_valid():
            order = order_form.save(commit=False)
            pid = request.POST.get('client_secret').split('_secret')[0]
            order.stripe_pid = pid
            order.original_cart = json.dumps(cart)
            order.save()
            for item_id, quantity in cart.items():
                try:
                    product = Product.objects.get(id=item_id)
                    if isinstance(quantity, int):
                        order_line_item = OrderLineItem(
                            order=order,
                            product=product,
                            quantity=quantity,
                        )
                        order_line_item.save()
                    order_line_item.save()
                except Product.DoesNotExist:
                    messages.error(request, (
                        "One of the products wasn't recognized in our database. \
                        Please call us for assistance with this order.")
                    )
                    order.delete()
                    return redirect(reverse('cart'))

            request.session['save_info'] = 'save-info' in request.POST
            return redirect(reverse('checkout_success',
                            args=[order.order_number]))
        else:
            messages.error(request, "There was an error handling your form. \
                Please make sure the information you provided is correct.")
    else:
        cart = request.session.get('cart', {})
        if not cart:
            messages.error(request, "Your cart is empty at the moment")
            return redirect(reverse('products'))

        current_cart = cart_contents(request)
        total = current_cart['grand_total']
        stripe_total = round(total * 100)
        stripe.api_key = stripe_secret_key
        intent = stripe.PaymentIntent.create(
            amount=stripe_total,
            currency=settings.STRIPE_CURRENCY
        )

        if request.user.is_authenticated:
            try:
                profile = UserProfile.objects.get(user=request.user)
                order_form = OrderForm(initial={
                    'full_name': profile.default_full_name,
                    'email': profile.default_email,
                    'phone_number': profile.default_phone_number,
                    'country': profile.default_country,
                    'postcode': profile.default_postcode,
                    'town_or_city': profile.default_town_or_city,
                    'street_address1': profile.default_street_address1,
                    'street_address2': profile.default_street_address2,
                    'county': profile.default_county,
                })
            except UserProfile.DoesNotExist:
                order_form = OrderForm()

        else:
            order_form = OrderForm()

    if not stripe_public_key:
        messages.warning(request, 'Stripe public key is missing')

    template = 'checkout/checkout.html'
    context = {
        'order_form': order_form,
        'stripe_public_key': stripe_public_key,
        'client_secret': intent.client_secret,
    }

    return render(request, template, context)


def checkout_success(request, order_number):
    """ A view to handle successfull checkouts """
    save_info = request.session.get('save_info')
    order = get_object_or_404(Order, order_number=order_number)

    if request.user.is_authenticated:
        profile = UserProfile.objects.get(user=request.user)
        order.user_profile = profile
        order.save()

        if save_info:
            profile_data = {
                'default_full_name': order.full_name,
                'default_email': order.email,
                'default_phone_number': order.phone_number,
                'default_country': order.country,
                'default_postcode': order.postcode,
                'default_town_or_city': order.town_or_city,
                'default_street_address1': order.street_address1,
                'default_street_address2': order.street_address2,
                'default_county': order.county,
            }
            user_profile_form = UserProfileForm(profile_data, instance=profile)
            if user_profile_form.is_valid():
                user_profile_form.save()

    messages.success(request, f'Order: {order_number} \
        Your order was successfully processed.')

    if 'cart' in request.session:
        del request.session['cart']

    template = 'checkout/checkout_success.html'
    context = {
        'order': order,
    }

    return render(request, template, context)

checkout/templates/checkout/checkout.html
{% extends "base.html" %}
{% load static %}
{% load cart_tools %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'checkout/css/checkout.css' %}">
{% endblock %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="body-container container-fluid px-1 px-sm-3 my-1 my-sm-3">
        <div class="row body-products justify-content-center mx-0">
            <div class="row w-100">
                <div class="col text-center mt-3">
                    <!--  Header Text  -->
                    <h3 class="text-muted">Checkout</h3>
                    <hr class="w-75 mb-3">
                </div>
            </div>
            <div class="row w-100 justify-content-center mt-3 px-1 px-md-3">
                <!--  Order summary / Cart items and prices  -->
                <div class="col-12 col-md-10 col-lg-6 order-lg-last px-0 pb-3 pl-lg-2">
                    <p class="mb-1 mb-md-3">Order Summary - <strong>{{ product_count }} item{% if product_count > 1 %}s{% endif %}</strong></p>
                    <div class="col order-summary border border-black rounded-0 pt-3 pb-2 pb-md-3">
                        <div class="row">
                            <div class="col-6 col-md-7">
                                <p class="mb-1 d-none d-md-block">Product:</p>
                                <p class="mb-1 d-md-none"><small>Product:</small></p>
                            </div>
                            <div class="col-1 p-0">
                                <p class="mb-1 d-none d-md-block">Qty:</p>
                                <p class="mb-1 d-md-none"><small>Qty:</small></p>
                            </div>
                            <div class="col-2 pl-2">
                                <p class="mb-1 d-none d-md-block">Price:</p>
                                <p class="mb-1 d-md-none"><small>Price:</small></p>
                            </div>
                            <div class="col-3 col-md-2 pl-0 text-right">
                                <p class="mb-1 d-none d-md-block">Total:</p>
                                <p class="mb-1 d-md-none"><small>Total:</small></p>
                            </div>
                        </div>
                        {% for item in cart_items %}
                            <div class="row py-1">
                                <div class="col-6 col-md-7">
                                    <p class="my-0 d-none d-md-block">{{ item.product.brand }} - {{ item.product }}</p>
                                    <p class="my-0 d-md-none"><small>{{ item.product.brand }} - {{ item.product }}</small></p>
                                </div>
                                <div class="col-1 p-0">
                                    <p class="my-0 d-none d-md-block">{{ item.quantity }}</p>
                                    <p class="my-0 d-md-none"><small>{{ item.quantity }}</small></p>
                                </div>
                                <div class="col-2 pl-2">
                                    <p class="my-0 d-none d-md-block">${{ item.product.brand.price }}</p>
                                    <p class="my-0 d-md-none"><small>${{ item.product.brand.price }}</small></p>
                                </div>
                                <div class="col-3 col-md-2 pl-0 text-right">
                                    <p class="my-0 d-none d-md-block"><strong>${{ item.product.brand.price | calc_subtotal:item.quantity }}</strong></p>
                                    <p class="my-0 d-md-none"><small><strong>${{ item.product.brand.price | calc_subtotal:item.quantity }}</strong></small></p>
                                </div>
                            </div>
                        {% endfor %}
                        <!--  Info on total cost and shipping  -->
                        <div class="row m-0">
                            <div class="col-8 border-top border-muted rounded-0 p-0 d-none d-md-block">
                                <p class="my-1"><strong>Order Total:</strong></p>
                                <p class="my-1"><strong>Delivery:</strong></p>
                                <p class="my-1"><strong>Grand Total:</strong></p>
                            </div>
                            <div class="col-8 border-top border-muted rounded-0 p-0 d-md-none">
                                <p class="my-1"><strong><small>Total:</small></strong></p>
                                <p class="my-1"><strong><small>Delivery:</small></strong></p>
                                <p class="my-1"><strong><small>Grand Total:</small></strong></p>
                            </div>
                            <div class="col-4 border-top border-muted rounded-0 p-0 text-right d-none d-md-block">
                                <p class="my-1">${{ total | floatformat:2 }}</p>
                                <p class="my-1">${{ delivery | floatformat:2 }}</p>
                                <p class="my-1"><strong>${{ grand_total | floatformat:2 }}</strong></p>
                            </div>
                            <div class="col-4 border-top border-muted rounded-0 p-0 text-right d-md-none">
                                <p class="my-1"><small>${{ total | floatformat:2 }}</small></p>
                                <p class="my-1"><small>${{ delivery | floatformat:2 }}</small></p>
                                <p class="my-1"><strong><small>${{ grand_total | floatformat:2 }}</small></strong></p>
                            </div>
                        </div>
                    </div>
                </div>
                <!--  Order form for making purchase  -->
                <div class="col-12 col-md-10 col-lg-6 px-0 pr-lg-2">
                    <p class="mb-1 d-none d-md-block">Please fill out the form to complete your order</p>
                    <div class="col-12 d-md-none p-0 m-0 text-center">
                        <p class="mb-2 small"><strong>Please fill out the form to complete your order</strong></p>
                    </div>
                    <form action="{% url 'checkout' %}" method="POST" id="payment-form">
                        {% csrf_token %}
                        <fieldset class="rounded-0">
                            <legend class="fieldset-label small mb-2">Details</legend>
                            {{ order_form.full_name | as_crispy_field }}
                            {{ order_form.email | as_crispy_field }}
                        </fieldset>
                        <fieldset class="rounded-0">
                            <legend class="fieldset-label small mb-2">Delivery</legend>
                            {{ order_form.phone_number | as_crispy_field }}
                            {{ order_form.country | as_crispy_field }}
                            {{ order_form.street_address1 | as_crispy_field }}
                            {{ order_form.street_address2 | as_crispy_field }}
                            {{ order_form.postcode | as_crispy_field }}
                            {{ order_form.town_or_city | as_crispy_field }}
                            {{ order_form.county | as_crispy_field }}
                            <div class="form-check form-check-inline custom-control custom-checkbox pl-0 mb-2">
                                {% if user.is_authenticated %}
                                    <input class="form-check-input custom-control-input" type="checkbox" name="save-info" id="id-save-info" checked>
                                    <label class="form-check-label custom-control-label" for="id-save-info">Save details to your profile</label>
                                {% else %}
                                    <label class="form-check-label" for="id-save-info">
                                        <a href="{% url 'account_signup' %}" class="text-black">Create an account </a>or
                                        <a href="{% url 'account_login' %}" class="text-black"> login </a>to save information.
                                    </label>
                                {% endif %}
                            </div>
                        </fieldset>
                        <fieldset class="rounded-0">
                            <legend class="fieldset-label small mb-2">Payment</legend>
                            <div class="p-2" id="card-element">
                                <!-- Handles Stripe card payments -->
                            </div>
                            <div class="p-2" id="card-error" role="alert">
                                <!-- To display errors in the form -->
                            </div>
                            <!-- Pass the client secret to the view, to get the payment intent id -->
                            <input type="hidden" value="{{ client_secret }}" name="client_secret">
                        </fieldset>
                        <!--  Total summary, submit or go back. For small, and for large screens  -->
                        <div class="row w-100 m-0 pb-3">
                            <div class="col-8 p-0 d-md-none">
                                <span class="ml-1"><small><i class="fas fa-exclamation"></i> <u>Your card will be charged <strong>${{ grand_total|floatformat:2 }}</strong></u></small></span>
                                <br />
                                <a href="{% url 'cart' %}">
                                    <span><small><i class="fa fa-shopping-cart"></i><strong> Make changes to your cart</strong></small></span>
                                </a>
                            </div>
                            <div class="col-8 p-0 d-none d-md-block">
                                <span class="icon mx-2"><i class="fas fa-exclamation"></i></span>
                                <span><u>Your card will be charged <strong>${{ grand_total|floatformat:2 }}</strong></u></span>
                                <br />
                                <a href="{% url 'cart' %}" class="mx-1">
                                    <span class="icon"><i class="fa fa-shopping-cart"></i></span>
                                    <span><strong>Make changes to your cart</strong></span>
                                </a>
                            </div>
                            <div class="col-4 p-0">
                                <button id="submit-button" class="btn btn-black rounded-0 float-right my-1">
                                    <span>Checkout</span>
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="row w-100">
                <div class="col text-center">
                    <hr class="w-75 mb-3">
                </div>
            </div>
        </div>
    </div>
    <div id="loading-overlay">
        <h1 class="text-dark logo-font loading-spinner">
            <span class="icon"><i class="fas fa-sync-alt fa-spin"></i></span>
        </h1>
    </div>
{% endblock %}

{% block page_footer %}
    <div class="container footer-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    {{ stripe_public_key|json_script:"id_stripe_public_key" }}
    {{ client_secret|json_script:"id_client_secret" }}
    <script src="{% static 'checkout/js/stripe_elements.js' %}"></script>

    {% if user.is_authenticated %}
        <script type="text/javascript">
            {% if order_form.full_name.value == None %}
                var fullName = "{{ user.first_name }} {{ user.last_name }}";
                $('#id_full_name').val(fullName);
            {% endif %}
            {% if order_form.email.value == None %}
                var userEmail = "{{ user.email }}";
                $('#id_email').val(userEmail);
            {% endif %}
        </script>
    {% endif %}
{% endblock %}