cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_cart, name='cart'),
    path('add/<item_id>', views.add_to_cart, name='add_to_cart'),
    path('adjust/<item_id>/', views.adjust_cart, name='adjust_cart'),
    path('remove/<item_id>/', views.remove_from_cart, name='remove_from_cart'),
]

myfitness/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('programs/', include('programs.urls')),
    path('about/', include('about.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.all_products, name='products'),
    path('<int:product_id>/', views.product, name='product'),
    path('manage/', views.product_management, name='product_management'),
    path('add_product/', views.add_product, name='add_product'),
    path('edit_product/<int:product_id>/',
         views.edit_product, name='edit_product'),
    path('delete_product/<int:product_id>/',
         views.delete_product, name='delete_product'),
    path('add_brand/', views.add_brand, name='add_brand'),
    path('edit_brand/<int:brand_id>/', views.edit_brand, name='edit_brand'),
    path('delete_brand/<int:brand_id>/',
         views.delete_brand, name='delete_brand'),
    path('add_producer/', views.add_producer,
         name='add_producer'),
    path('edit_producer/<int:producer_id>/',
         views.edit_producer, name='edit_producer'),
    path('delete_producer/<int:producer_id>/',
         views.delete_producer, name='delete_producer'),

    path('ajax/load-brands/', views.load_brands, name='load_brands'),
]

products/models.py
from django.db import models


class Category(models.Model):

    class Meta:
        verbose_name_plural = "Categories"

    name = models.CharField(max_length=254, null=True)
    friendly_name = models.CharField(max_length=254, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name


class Producer(models.Model):
    name = models.CharField(max_length=254, null=True)
    friendly_name = models.CharField(max_length=254, null=True, blank=True)

    def __str__(self):
        return self.friendly_name

    def get_friendly_name(self):
        return self.friendly_name


class Brand(models.Model):
    category = models.ForeignKey(
        'Category',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
    )
    producer = models.ForeignKey(
        'Producer',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
    )
    name = models.CharField(max_length=254, null=True)
    friendly_name = models.CharField(max_length=254, null=True, blank=True)
    spec = models.CharField(max_length=254, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    rating = models.DecimalField(
        max_digits=6, decimal_places=2, null=True, blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2, null=True)

    def __str__(self):
        return self.friendly_name

    def get_friendly_name(self):
        return self.friendly_name


class Product(models.Model):

    class Meta:
        ordering = ('pk',)

    producer = models.ForeignKey(
        'Producer',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
    )
    brand = models.ForeignKey(
        'Brand',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
    )
    name = models.CharField(max_length=254, null=True)
    friendly_name = models.CharField(max_length=254, null=True, blank=True)
    sku = models.CharField(max_length=254, null=True, blank=True)
    ingredients = models.TextField(null=True, blank=True)
    stock = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    image = models.ImageField(null=True, blank=True)
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    thumbnail = models.BooleanField(default=False)

    def __str__(self):
        return self.friendly_name

    def get_friendly_name(self):
        return self.friendly_name

products/forms.py
from django import forms
from .widgets import CustomClearableFileInput
from .models import Producer, Brand, Product, Category


class ProducerForm(forms.ModelForm):

    class Meta:
        model = Producer
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'border-black rounded-0'


class BrandForm(forms.ModelForm):

    class Meta:
        model = Brand
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        categories = Category.objects.all()
        friendly_names = [(c.id, c.get_friendly_name()) for c in categories]

        self.fields['category'].choices = friendly_names

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'border-black rounded-0'


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'

    image = forms.ImageField(label='Image',
                             required=False, widget=CustomClearableFileInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['brand'].queryset = Brand.objects.none()

        if 'producer' in self.data:
            try:
                producer_id = int(self.data.get('producer'))
                self.fields['brand'].queryset = Brand.objects.filter(
                        producer_id=producer_id
                    ).order_by('friendly_name')
            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields['brand'].queryset = (
                self.instance.producer.brand_set.order_by('friendly_name'))

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'border-black rounded-0'

products/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from .models import Product, Brand, Producer, Category
from .forms import ProductForm, BrandForm, ProducerForm


def all_products(request):
    """ A view to show, sort and search all products """

    categories = Category.objects.all()
    producers = Producer.objects.all()
    brands = Brand.objects.all()
    products = Product.objects.all()
    query = None
    current_category = None
    sort = None
    direction = None

    if request.GET:

        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            if sortkey == 'name':
                sortkey = 'friendly_name'
            if sortkey == 'category':
                sortkey = 'category__name'
            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            brands = brands.order_by(sortkey)

        if 'category' in request.GET:
            current_category = request.GET['category'].split(',')
            brands = brands.filter(category__name__in=current_category)
            current_category = Category.objects.filter(
                name__in=current_category)

        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(
                    request, "You didn't enter any search criteria!"
                )
                return redirect(reverse('products'))

            queries = Q(
                friendly_name__icontains=query
            ) | Q(
                name__icontains=query
            ) | Q(
                description__icontains=query
            )
            brands = brands.filter(queries)

    current_sorting = f'{sort}_{direction}'

    context = {
        'products': products,
        'producers': producers,
        'brands': brands,
        'search_term': query,
        'categories': categories,
        'current_category': current_category,
        'current_sorting': current_sorting,
    }

    return render(request, 'products/products.html', context)


def product(request, product_id):
    """ A view to show the product details """

    product = get_object_or_404(Product, pk=product_id)
    categories = Category.objects.all()
    producers = Producer.objects.all()
    brands = Brand.objects.all()
    products = Product.objects.all()

    context = {
        'product': product,
        'products': products,
        'producers': producers,
        'brands': brands,
        'categories': categories,
    }

    return render(request, 'products/product_detail.html', context)


@login_required
def product_management(request):
    """ Managing products, brands and producer objects """
    if not request.user.is_superuser:
        messages.error(request, "You're not authorized to do this")
        return redirect(reverse('home'))

    products = Product.objects.all()
    brands = Brand.objects.all()
    producers = Producer.objects.all()

    context = {
        'products': products,
        'brands': brands,
        'producers': producers,
    }

    return render(request, 'products/product_management.html', context)


@login_required
def add_product(request):
    """ Adding new Product items to the store """
    if not request.user.is_superuser:
        messages.error(request, "You're not authorized to do this")
        return redirect(reverse('home'))

    if request.method == 'POST':
        product_form = ProductForm(request.POST, request.FILES)
        if product_form.is_valid():
            product_form.save()
            messages.success(request, "Product was added successfully")
            return redirect(reverse('product_management'))
        else:
            messages.error(
                request,
                'Failed to add product. Ensure fields are filled in properly')
    else:
        product_form = ProductForm()

    template = 'products/add_product.html'
    context = {
        'product_form': product_form,
    }

    return render(request, template, context)


@login_required
def edit_product(request, product_id):
    """ Make changes to products in store """
    if not request.user.is_superuser:
        messages.error(request, "You're not authorized to do this")
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        product_form = ProductForm(
            request.POST, request.FILES, instance=product)
        if product_form.is_valid:
            product_form.save()
            messages.success(request, 'Successfully updated')
            return redirect(reverse('product_management'))
        else:
            messages.error(
                request,
                'Failed to update product. Make sure the form is vaild.')
    else:
        product_form = ProductForm(instance=product)
        messages.info(request, f"You're now making changes to \
            {product.brand} - {product.friendly_name}")

    template = 'products/edit_product.html'
    context = {
        'product': product,
        'product_form': product_form,
    }

    return render(request, template, context)


def load_brands(request):
    """
    A view to return related brands with selected
    producer when creating a new product
    """
    producer_id = request.GET.get('producer')
    brands = Brand.objects.filter(
        producer_id=producer_id).order_by('friendly_name')

    template = 'includes/brands_dropdown_options.html'
    context = {
        'brands': brands,
    }
    return render(request, template, context)


@login_required
def delete_product(request, product_id):
    """ Deletes a product from the store """
    if not request.user.is_superuser:
        messages.error(request, "You're not authorized to do this")
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    product.delete()
    messages.success(request, 'Product deleted!')
    return redirect(reverse('product_management'))


@login_required
def add_brand(request):
    """ Adding new Brand items to the store """
    if not request.user.is_superuser:
        messages.error(request, "You're not authorized to do this")
        return redirect(reverse('home'))

    if request.method == 'POST':
        brand_form = BrandForm(request.POST, request.FILES)
        if brand_form.is_valid():
            brand_form.save()
            messages.success(request, "Brand was added successfully")
            return redirect(reverse('product_management'))
        else:
            messages.error(
                request,
                'Failed to add brand. Ensure fields are filled in properly')
    else:
        brand_form = BrandForm()

    template = 'products/add_brand.html'
    context = {
        'brand_form': brand_form,
    }

    return render(request, template, context)


@login_required
def edit_brand(request, brand_id):
    """ Make changes to a brand """
    if not request.user.is_superuser:
        messages.error(request, "You're not authorized to do this")
        return redirect(reverse('home'))

    brand = get_object_or_404(Brand, pk=brand_id)
    if request.method == 'POST':
        brand_form = BrandForm(request.POST, request.FILES, instance=brand)
        if brand_form.is_valid:
            brand_form.save()
            messages.success(request, 'Successfully updated')
            return redirect(reverse('product_management'))
        else:
            messages.error(
                request,
                'Failed to update brand. Make sure the form is vaild.')
    else:
        brand_form = BrandForm(instance=brand)
        messages.info(
            request, f"You're now making changes to {brand.friendly_name}")

    template = 'products/edit_brand.html'
    context = {
        'brand': brand,
        'brand_form': brand_form,
    }

    return render(request, template, context)


@login_required
def delete_brand(request, brand_id):
    """ Deletes a brand from the store """
    if not request.user.is_superuser:
        messages.error(request, "You're not authorized to do this")
        return redirect(reverse('home'))

    brand = get_object_or_404(Brand, pk=brand_id)
    brand.delete()
    messages.success(request, 'Brand deleted!')
    return redirect(reverse('product_management'))


@login_required
def add_producer(request):
    """ Adding new Producer items to the store """
    if not request.user.is_superuser:
        messages.error(request, "You're not authorized to do this")
        return redirect(reverse('home'))

    if request.method == 'POST':
        producer_form = ProducerForm(request.POST, request.FILES)
        if producer_form.is_valid():
            producer_form.save()
            messages.success(request, "Producer was added successfully")
            return redirect(reverse('product_management'))
        else:
            messages.error(
                request,
                'Failed to add producer. Ensure fields are filled in properly',
            )
    else:
        producer_form = ProducerForm()

    template = 'products/add_producer.html'
    context = {
        'producer_form': producer_form,
    }

    return render(request, template, context)


@login_required
def edit_producer(request, producer_id):
    """ Make changes to a producer """
    if not request.user.is_superuser:
        messages.error(request, "You're not authorized to do this")
        return redirect(reverse('home'))

    producer = get_object_or_404(Producer, pk=producer_id)
    if request.method == 'POST':
        producer_form = ProducerForm(
            request.POST, request.FILES, instance=producer)
        if producer_form.is_valid:
            producer_form.save()

products/templates/products/add_brand.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="body-container container-fluid px-1 px-sm-3 my-1 my-sm-3">
        <div class="row body-products justify-content-center mx-0">
            <div class="row w-100">
                <div class="col text-center mt-3">
                    <!--  Header Text  -->
                    <h3 class="text-muted">Product Management</h3>
                    <hr class="w-75 mb-3">
                </div>
            </div>
            <div class="row w-100 m-3 justify-content-center">
                <div class="col-12 col-md-8 col-lg-6">
                    <h5>Add a new brand</h5>
                    <!--  Form to add info for creating new brand  -->
                    <p class="text-muted small">Brand refers to the different type of product brand, which can have more flavors, sizes or other variations.</p>
                    <form id="brand-form" method="POST" action="{% url 'add_brand' %}" class="form m-0" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ brand_form | crispy }}
                        <a href="{% url 'product_management' %}" class="btn btn-black rounded-0">Cancel</a>
                        <button type="submit" class="btn btn-black rounded-0 float-right">Add Brand</button>
                    </form>
                </div>
            </div>
            <div class="row w-100">
                <div class="col text-center mt-3">
                    <hr class="w-75 mb-3">
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block page_footer %}
    <div class="container footer-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script type="text/javascript">
        // Adding a "blank" first option to give same look as on rest of page
        $('#id_category').prepend('<option value="0" selected disabled>---------</option>');
        // Setting max, min and steps to rating and price inputs
        $(function() {
            $('#id_rating').attr({step:"0.5", max:"5", min:"1"});
            $('#id_price').attr({min:"0"});
        });
    </script>
{% endblock %}

products/templates/products/add_producer.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="body-container container-fluid px-1 px-sm-3 my-1 my-sm-3">
        <div class="row body-products justify-content-center mx-0">
            <div class="row w-100">
                <div class="col text-center mt-3">
                    <!--  Header Text  -->
                    <h3 class="text-muted">Product Management</h3>
                    <hr class="w-75 mb-3">
                </div>
            </div>
            <div class="row w-100 m-3 justify-content-center">
                <div class="col-12 col-md-8 col-lg-6">
                    <h5>Add a new producer</h5>
                    <!--  Form to add info for creating new producer  -->
                    <p class="text-muted small">Producer refers to manufacturer of a brand and products</p>
                    <form id="producer-form" method="POST" action="{% url 'add_producer' %}" class="form m-0">
                        {% csrf_token %}
                        {{ producer_form | crispy }}
                        <a href="{% url 'product_management' %}" class="btn btn-black rounded-0">Cancel</a>
                        <button type="submit" class="btn btn-black rounded-0 float-right">Add Producer</button>
                    </form>
                </div>
            </div>
            <div class="row w-100">
                <div class="col text-center mt-3">
                    <hr class="w-75 mb-3">
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block page_footer %}
    <div class="container footer-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

products/templates/products/add_product.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="body-container container-fluid px-1 px-sm-3 my-1 my-sm-3">
        <div class="row body-products justify-content-center mx-0">
            <div class="row w-100">
                <div class="col text-center mt-3">
                    <!--  Header Text  -->
                    <h3 class="text-muted">Product Management</h3>
                    <hr class="w-75 mb-3">
                </div>
            </div>
            <div class="row w-100 m-3 justify-content-center">
                <div class="col-12 col-md-8 col-lg-6">
                    <!--  Form to add info for creating new product  -->
                    <h5>Add a new product</h5>
                    <p class="text-muted small">New product refers to new flavor, size or other variation for one brand.</p>
                    <form id="product-form" data-brands-url="{% url 'load_brands' %}" method="POST" action="{% url 'add_product' %}" class="form m-0" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for field in product_form %}
                            {% if field.name == 'thumbnail' %}
                                {% include 'includes/checkbox.html' %}
                            {% elif field.name != 'image' %}
                                {{ field | as_crispy_field }}
                            {% else %}
                                {{ field }}
                            {% endif %}
                        {% endfor %}
                        <a href="{% url 'product_management' %}" class="btn btn-black rounded-0">Cancel</a>
                        <button type="submit" class="btn btn-black rounded-0 float-right">Add Product</button>
                    </form>
                </div>
            </div>
            <div class="row w-100">
                <div class="col text-center mt-3">
                    <hr class="w-75 mb-3">
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block page_footer %}
    <div class="container footer-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script type="text/javascript">
        // Handling look of upload image
        $("#new-image").change(function() {
            var file = $("#new-image")[0].files[0];
            $("#filename").text(`Image will be set to: ${file.name}`);
        });
        // Displaying only the brands connected to the selected producer
        $("#id_producer").change(function () {
            var url = $("#product-form").attr("data-brands-url");
            var producerId = $(this).val();
            $.ajax({
                url: url,
                data: {
                    'producer': producerId
                },
                success: function (data) {
                    $("#id_brand").html(data);
                }
            });
        });
    </script>
{% endblock %}

products/templates/products/edit_brand.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="body-container container-fluid px-1 px-sm-3 my-1 my-sm-3">
        <div class="row body-products justify-content-center mx-0">
            <div class="row w-100">
                <div class="col text-center mt-3">
                    <!--  Header Text  -->
                    <h3 class="text-muted">Product Management</h3>
                    <hr class="w-75 mb-3">
                </div>
            </div>
            <div class="row w-100 m-3 justify-content-center">
                <div class="col-12 col-md-8 col-lg-6">
                    <h5>Edit brand</h5>
                    <!--  Form to edit brand  -->
                    <form method="POST" action="{% url 'edit_brand' brand.id %}" class="form m-2">
                        {% csrf_token %}
                        {{ brand_form | crispy }}
                        <a href="{% url 'products' %}" class="btn btn-black rounded-0">Cancel</a>
                        <button type="submit" class="btn btn-black rounded-0 float-right">Save Update</button>
                    </form>
                </div>
            </div>
            <div class="row w-100">
                <div class="col text-center mt-3">
                    <hr class="w-75 mb-3">
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block page_footer %}
    <div class="container footer-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script type="text/javascript">
        // handling max, min and step values for rating and price
        $(function() {
            $('#id_rating').attr({step:"0.5", max:"5", min:"1"});
            $('#id_price').attr({min:"0"});
        });
    </script>
{% endblock %}

products/templates/products/edit_producer.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="body-container container-fluid px-1 px-sm-3 my-1 my-sm-3">
        <div class="row body-products justify-content-center mx-0">
            <div class="row w-100">
                <div class="col text-center mt-3">
                    <!--  Heading Text  -->
                    <h3 class="text-muted">Product Management</h3>
                    <hr class="w-75 mb-3">
                </div>
            </div>
            <div class="row w-100 m-3 justify-content-center">
                <div class="col-12 col-md-8 col-lg-6">
                    <h5>Edit producer</h5>
                    <!--  Form to edit producer  -->
                    <form method="POST" action="{% url 'edit_producer' producer.id %}" class="form m-2">
                        {% csrf_token %}
                        {{ producer_form | crispy }}
                        <a href="{% url 'product_management' %}" class="btn btn-black rounded-0">Cancel</a>
                        <button type="submit" class="btn btn-black rounded-0 float-right">Save Update</button>
                    </form>
                </div>
            </div>
            <div class="row w-100">
                <div class="col text-center mt-3">
                    <hr class="w-75 mb-3">
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block page_footer %}
    <div class="container footer-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

products/templates/products/edit_product.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="body-container container-fluid px-1 px-sm-3 my-1 my-sm-3">
        <div class="row body-products justify-content-center mx-0">
            <div class="row w-100">
                <div class="col text-center mt-3">
                    <!--  Header Text  -->
                    <h3 class="text-muted">Product Management</h3>
                    <hr class="w-75 mb-3">
                </div>
            </div>
            <div class="row w-100 m-3 justify-content-center">
                <div class="col-12 col-md-8 col-lg-6">
                    <h5>Edit product</h5>
                    <!--  Form to edit product  -->
                    <form method="POST" action="{% url 'edit_product' product.id %}" class="form m-2" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for field in product_form %}
                            {% if field.name == 'thumbnail' %}
                                {% include 'includes/checkbox.html' %}
                            {% elif field.name != 'image' %}
                                {{ field | as_crispy_field }}
                            {% else %}
                                {{ field }}
                            {% endif %}
                        {% endfor %}
                        <a href="{% url 'products' %}" class="btn btn-black rounded-0">Cancel</a>
                        <button type="submit" class="btn btn-black rounded-0 float-right">Save Update</button>
                    </form>
                </div>
            </div>
            <div class="row w-100">
                <div class="col text-center mt-3">
                    <hr class="w-75 mb-3">
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block page_footer %}
    <div class="container footer-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script type="text/javascript">
        // Handling/styling new image field
        $("#new-image").change(function() {
            var file = $("#new-image")[0].files[0];
            $("#filename").text(`Image will be set to: ${file.name}`);
        });
    </script>
{% endblock %}